### ISSUE TITLE
Mattermost Server Down?

### ISSUE THREAD

**Issue by Cryptophobia** [mantl/mantl#1892]
Is the mattermost server down? I cannot seem to connect, it gives me 526 errors and bad SSL certificate errors.

**Comment by thomasvincent** [comment]
Hacked by slack? ;)

**Comment by Theaxiom** [comment]
Seems okay to me. I'm not experiencing any issues.

**Comment by Cryptophobia** [comment]
So am I the only one not able to access it?

**Comment by Theaxiom** [comment]
What client are you using? I tried with Android app, website and Mac OSX
app and they all work.

**Comment by Cryptophobia** [comment]
@Theaxiom Firefox

**Comment by Theaxiom** [comment]
Try installing the desktop client and pointing it at
https://mattermost.dynamictivity.com

**Comment by Theaxiom** [comment]
Did it work?

**Comment by Theaxiom** [comment]
Sorry guys, Mattermost is currently down at this moment in time due to a Digital Ocean outage: http://status.digitalocean.com

**Comment by Theaxiom** [comment]
Just received an update from Digital Ocean:

Hello,

We would like to apologize and take full responsibility for the issues you’ve experienced today. We want you to know that fixing them is absolutely our top priority.

At 06:43 UTC, multiple redundant power sources in our SFO2 datacenter failed temporarily, causing a large number of Droplets and core systems, including networking, to go down. We have restored power and networking, and are currently working to bring all affected Droplets safely online.

Following the full power recovery, we started to experience delays in event processing. Our engineering team was able to isolate the root cause. We will update the status page once all events are processing without delay and will publish further details to our blog once we’ve conducted a full post mortem.

We’ll continue to post updates on our status page as we have them:

https://status.digitalocean.com

We understand how much this is impacting you, and we’re currently all hands on deck trying to resolve the issues as quickly as possible. We’re working to understand the various causes of the problems and we are committed to finding permanent solutions. Following the full resolution of this issue, we will provide you with an update and we will separately follow up regarding SLA credits. We sincerely thank you for your patience and understanding in the meantime.

With love,
DigitalOcean Platform Support

**Comment by Theaxiom** [comment]
Mattermost is back up now, the Digital Ocean issue is starting to resolve. It is quite unfortunate about Digital Ocean, I am sure that is really going to hurt them.

**Comment by Cryptophobia** [comment]
@Theaxiom : Travis, can you enable tunnel connections to your Mattermost server?

I am not able to access it even with the Mattermost desktop client:

`Cannot connect to Mattermost`

`ERR_TUNNEL_CONNECTION_FAILED (-111)`

is the error I get from everywhere.

**Comment by Theaxiom** [comment]
Are you behind a proxy or something @Cryptophobia ? The server is enforcing HTTPS btw.

**Comment by Theaxiom** [comment]
What browser are you using @Cryptophobia ? I would try clearing out your HSTS certificate cache in your browser, I am betting that's it since I changed SSL certificates. You can use these instructions: https://www.thesslstore.com/blog/clear-hsts-settings-chrome-firefox/

**Comment by Theaxiom** [comment]
Also, try checking your proxy settings of your browser. You may have something in there you don't know about: https://www.servertastic.com/support/error-111-net-err-tunnel-connection-failed-unknown-error

**Comment by Theaxiom** [comment]
One last thing I can think of, CloudFlare blocks users who have malware installed. You can try scanning for malware on your computer: https://www.malwarebytes.com

**Comment by Cryptophobia** [comment]
@Theaxiom Hey, I tried all those things but nothing is working. I am using Firefox as the browser/the desktop client and going through an http proxy.

I was able to connect until you change the certificate. Do you think CloudFlare is blocking my proxied connection?

**Comment by Cryptophobia** [comment]
After trying different things I was able to get in again. I don't know for how long this bliss will last... lol

**Comment by Theaxiom** [comment]
I'm sure it was the HSTS, it is very touchy. You should be fine indefinitely now.
