### ISSUE TITLE
mantl.io website is down

### ISSUE THREAD

**Issue by brilong** [mantl/mantl#2019]
Not sure where to log this, but the website is down.  Is mantl still being actively developed?

**Comment by thomasvincent** [comment]
Its been down since June 4 from what I can tell. It was hosted by Cisco I believe. I pulled a copy off the internet Wayback machine and am going to move it to GitHub pages.

**Comment by brilong** [comment]
Interesting.  I'm actually a Cisco employee and I've been trying to track down who is still working on Mantl internally or if it was abandoned.  :)

**Comment by thomasvincent** [comment]
Brian, I have tried to reach out to Cisco internal resources and haven’t
been successful. From what I understand funding was cut internally and the
team laid off about six months ago. A couple of us are working on a revamp.
But we have questions about trademarks , and copyright.


On August 3, 2017 at 2:09:15 PM, Brian Long (notifications@github.com)
wrote:

Interesting. I'm actually a Cisco employee and I've been trying to track
down who is still working on Mantl internally or if it was abandoned. :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mantl/mantl/issues/2019#issuecomment-320090885>, or mute
the thread

**Comment by brilong** [comment]
I'm starting to ask around internally and I'll get back to you if I hear anything.  I believe the trademark and copyright issue needs to be addressed by Cisco Legal.

**Comment by Cryptophobia** [comment]
Are we bringing the website online at http://mantl.github.io/ ?

Any possibility we can buy the domain mantl.io or would that depend if we need to rename the project after addressing with Cisco Legal?

**Comment by Theaxiom** [comment]
@stevendborrelli Is it possible to get the DNS changed for Mantl.io?

**Comment by stevendborrelli** [comment]
I'm asking one of the folks I knew involved with the project.

**Comment by stevendborrelli** [comment]
I've identified the person who owns the domain. They need to check with their employer.

**Comment by brilong** [comment]
I've also sent out emails to a bunch of Cisco folks tied to the Mantl project to see if anyone knows how to get trademarks and copyright info transferred.

**Comment by Theaxiom** [comment]
Thanks @brilong and @stevendborrelli !

**Comment by kingdonb** [comment]
The website appears to be online right now, hot diggity

**Comment by Cryptophobia** [comment]
I am hitting cloudflare - 104.18.49.248 . This is still Cisco hosting the website, correct?
