### ISSUE TITLE
Require Ansible >= 2.1

### ISSUE THREAD

**Issue by stevendborrelli** [mantl/mantl#806]
The ansible lvg module has a bug that fails on GCE during a second run. It is fixed in master. 

Update requirements.txt to use 1.9.5 (or whatever the version is), when the fix is in a released version.

**Comment by eirslett** [comment]
Maybe this can be checked in terraform.yml, the same way that it checks that security-setup has been run? Then it would fail fast as well, instead of wasting hours of time debugging.

**Comment by stevendborrelli** [comment]
@eirslett that is a really good idea that we should implement once 1.9.5 is out. For now, @avnik is testing just using a local library.

**Comment by siddharthist** [comment]
As I noticed while investigating Ansible 2.0, Ansible never released a version 1.9.5. I'm going to change the header of this issue to reflect the next version number, which is 2.0. 

Reprinted from #1018 :
In my testing, the only issue I've had with ansible-playbook 2.0.0.2 has been mitchellh/vagrant#6793 and the empty tag list in the common role (which is fixed in #1017). We need to wait for Vagrant 1.8.3, but as soon as that is out, we should test with Ansible 2.0.0.2 and move our requirements to the latest version of both.

**Comment by geerlingguy** [comment]
(Should be Vagrant 1.8.2, btw).

**Comment by siddharthist** [comment]
@geerlingguy Updated, thanks for the catch!

**Comment by siddharthist** [comment]
Good news! v1.8.4 is out, we can start migrating to Ansible 2.0!

**Comment by siddharthist** [comment]
Once we use Ansible 2.1 we can eliminate library/kube.py in favor of the [official module](https://docs.ansible.com/ansible/kubernetes_module.html).
